# -*- coding: utf-8 -*-
"""Project2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SqH1SSSR2Pve33hIVQhfpa0ZZFeKKHAc

Importing libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""Importing dataset"""

dataset = pd.read_excel('advertising_sales_data.xlsx')

"""Checking for missing values"""

print(dataset.isnull().sum())

print(dataset.shape)

"""Dropping rows with missing data"""

dataset = dataset.dropna()
print(dataset.isnull().sum())

"""Average amount spent on TV advertising"""

print('Average Expenditure:-')
 print(f"TV: {dataset['TV'].mean():.2f}")
 print(f"Radio: {dataset['Radio'].mean():.2f}")
 print(f"Newspaper: {dataset['Newspaper'].mean():.2f}")

"""Making correlation matrix"""

import seaborn as sns
selected_dataset = dataset.iloc[:,1:]
cm = selected_dataset.corr()
sns.heatmap(cm, annot = True, cmap='Blues', fmt = '0.2f')
plt.title('Correlation Matrix')
plt.show()

"""Training a multiple linear regression model"""

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

x = dataset.iloc[:,1:4].values
y = dataset.iloc[:,4].values

"""Dividing the dataset into training and testing sets"""

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size = 0.2, random_state=1)

"""Training the model on the training set"""

lr = LinearRegression()
lr.fit(x_train,y_train)

"""Finding the values of the intercept and coefficients in the multiple linear regression equation"""

c = lr.intercept_
coeffs = lr.coef_
print(f'Intercept(c) =  {c}\nCoefficients = {coeffs}')

"""Visualising training set results"""

y_pred_train = lr.predict(x_train)

plt.scatter(y_train,y_pred_train, alpha=0.8)
plt.plot([y.min(),y.max()],[y.min(),y.max()], color='red', linestyle = '--', label = 'Perfect Prediction Line')
plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.title('Actual v/s Predicted Sales(Training Set)')
plt.legend()
plt.show()

"""Visualising testing set results"""

y_pred_test = lr.predict(x_test)

plt.scatter(y_test,y_pred_test, alpha = 0.8)
plt.plot([y.min(),y.max()],[y.min(),y.max()], color='red', linestyle = '--', label = 'Perfect Prediction Line')
plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.title('Actual v/s Predicted Sales(Testing Set)')
plt.legend()
plt.show()

"""Predicted sales for a new input expenditure"""

y_pred = lr.predict([[200,40,50]])
print(y_pred)

"""Training the model with normalised data"""

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)
lr_scaled = LinearRegression()
lr_scaled.fit(x_train_scaled, y_train)
y_pred_scaled = lr_scaled.predict(x_test_scaled)

from sklearn.metrics import mean_squared_error, r2_score
print("---Without Normalisation---\n")
print(f"R² Score: {r2_score(y_test,y_pred_test):.4f}")
print(f"MSE: {mean_squared_error(y_test,y_pred_test):.4f}")
print(f"Intercept: {lr.intercept_:.4f}")
print(f"Coefficients: {lr.coef_}\n\n")
print("---With Normalisation---\n")
print(f"R² Score: {r2_score(y_test,y_pred_scaled):.4f}")
print(f"MSE: {mean_squared_error(y_test,y_pred_scaled):.4f}")
print(f"Intercept: {lr_scaled.intercept_:.4f}")
print(f"Coefficients: {lr_scaled.coef_}")

"""Training the model only using radio and newspaper advertising expenditures"""

x_new = dataset.iloc[:,2:4].values
x_train_new,x_test_new,y_train,y_test=train_test_split(x_new,y, test_size=0.2, random_state=1)
lr_new = LinearRegression()
lr_new.fit(x_train_new,y_train)
y_pred_new = lr_new.predict(x_test_new)

"""Visualising the predictions of the new model"""

plt.scatter(y_test,y_pred_new, alpha = 0.8)
plt.plot([y.min(),y.max()], [y.min(),y.max()], color = 'red', linestyle = '--',label='Perfect Prediction Line')
plt.xlabel('Actual Sales')
plt.ylabel('Predicted Sales')
plt.legend()
plt.show()